### ISSUE TITLE
Don't multiply height/width by zoom level

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#106]
Use user entered height and width instead. The multiplication makes it very confusion because the end result is different from what the user entered.

(as reported by @oleedd in https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/89)

**Comment by oleedd** [comment]
I found two little bugs:
- it doesn't allow to set more than 600. Maybe not 800 but 600 is max?
![image](https://user-images.githubusercontent.com/36125949/60125823-49777e80-9795-11e9-9ad1-2842a313bbf9.png)
- the scrolling button slightly goes under the pop-up at any height/width/zoom.

**Comment by rpkamp** [comment]
Those seem like separate issues. Why are you adding them to this issue?

**Comment by oleedd** [comment]
Because the first is small. I think that there should be "6" instead of "8".
And the second problem was very big in #89. But it was well fixed. But the same problem for the scrolling button is left (which I found recently).
Of course if you need you can delete these comments and open new issues.

**Comment by rpkamp** [comment]
Fixed

**Comment by oleedd** [comment]
The pop-up size is still not the same at different zoom. I don't see changes after the update visually.
It also causes that if zoom < 100 - then not possible to use max height/width.

**Comment by rpkamp** [comment]
It seems it is setting the correct width/height in pixels, but since zoom > 100 it is multiplied by (zoom / 100), so 300px with zoom 200 will become 300 * (200 / 100) = 600 :slightly_frowning_face: 

I think I'm going to remove the "zoom" option and add a "font size" option and only scale using that. What do you think?

**Comment by oleedd** [comment]
No way to fix zoom?
About the "front size" option - I plan to make a cool mini-project with such name - but it is difficult and need to learn some things to give a clear solution. The sense is to zoom only the font without zooming anything else because now some nice but small fonts look like this:
![image](https://user-images.githubusercontent.com/36125949/60342826-2f1eea00-99bb-11e9-9400-6ecce81a7406.png)
or
![image](https://user-images.githubusercontent.com/36125949/60344796-0b11d780-99c0-11e9-9e3d-6f02d18c2bad.png)
And not possible to read something but there is much free space between strings.

**Comment by rpkamp** [comment]
There is a way to fix zoom, but using font size is a LOT easier, as you don't have to use the zoom in each and every calculation about width and height.

Plus, I rather doubt people are actually using zoom now, given the amount of bugs that were in there and the fact that no one reported them (apart from you, but I'm not sure you actually use it?)

**Comment by oleedd** [comment]
I don't use zoom but it is a very interesting option in terms of the programming aspect. I think I can fix it. It should be interesting.
What about my mini-project for small fonts above? I can't name it in a different way than "font size".

**Comment by oleedd** [comment]
I don't use zoom but it is a very interesting option in terms of the programming aspect. Also, it is useful for those who have bad eyesight. I think I can fix it. It should be interesting.
What about my mini-project for small fonts above? I can't name it in a different way than "font size".

**Comment by rpkamp** [comment]
I'm not sure how to solve your problem. Fonts are hard. I'd be interested to hear what you find!

**Comment by oleedd** [comment]
It is very difficult to solve this but I got a css solution (probably the only possible). But I want to first understand how it works. When done I will open an issue with explanations.
The problem is that your and my names are the same. No idea how to rename. So better if I or you fix zoom.

**Comment by rpkamp** [comment]
Let's see what you come up with, and then we'll see how we can combine that with zoom :+1:

**Comment by oleedd** [comment]
I have quickly found a solution to fix zoom. Just need to apply zoom to <ul `id="bookmarks"`. In addition, the scrolling button will no longer be so ugly big.

**Comment by oleedd** [comment]
I have quickly found a solution to fix zoom. Just need to apply zoom to `<ul id="bookmarks">`. In addition, the scrolling button will no longer be so ugly big.

**Comment by rpkamp** [comment]
Oh, that sounds like a plan. I'll try it somewhere next week 👍

**Comment by oleedd** [comment]
It becomes fixed if to just change this string:
`var htmlBodyElement = document.querySelector('#bookmarks');`
But also need to fix that the scrolling bar button slightly goes under the pop-up. It should be much harder (as the previous problem is too easy). Will try.

**Comment by oleedd** [comment]
It becomes fixed if to just change this string:
`var htmlBodyElement = document.querySelector('#bookmarks');`
But it is shorter to remove that string and replace `htmlBodyElement` by `bookmarks` here:
```javascript
if (zoom !== 100) {
    bookmarks.style.zoom = "".concat(zoom, "%");
}
```
But also need to fix that the scrolling bar button slightly goes under the pop-up. It should be much harder (as the previous problem is too easy). Will try.

**Comment by oleedd** [comment]
It becomes fixed if to just change this string:
`var htmlBodyElement = document.querySelector('#bookmarks');`
But it is shorter to remove that string and replace `htmlBodyElement` by `bookmarks` here:
```javascript
if (zoom !== 100) {
    bookmarks.style.zoom = "".concat(zoom, "%");
}
```
But also need to fix that the scrolling bar slightly goes under the pop-up. It should be much harder (as the previous problem is too easy). Will try.

**Comment by rpkamp** [comment]
> Will try.

Thanks! 

Could you please also check when you do that the popup that opens on right click opens in the right place? See https://github.com/rpkamp/chrome-minimal-bookmarks-tree/issues/114

**Comment by oleedd** [comment]
I don't see any problems - no idea how it looks if "popup opens too low".
If it is from some feedback - better to ask for a screenshot.
It works even faster if `zoom > 100` because less favicons in the pop-up. Chrome loads them too slow.

**Comment by oleedd** [comment]
I am not sure about the essence of #114.
It works even faster if `zoom > 100` because less favicons in the pop-up. Chrome loads them too slow.

**Comment by oleedd** [comment]
About "the scrolling bar slightly goes under the pop-up" - it is if `height > 595` - but I don't understand why.

**Comment by rpkamp** [comment]
Then we should limit the height to 595.

**Comment by oleedd** [comment]
It is not so big problem to do that. It just eats up to 5 pixels of the scrolling button but bookmarks are well.   I would like find out this.

**Comment by oleedd** [comment]
There is a big problem because dragula append temporary elements to `body` (not to `#bookmarks`). So either to set this, or to add scrolling in `html` (not in `#wrapper`).

**Comment by rpkamp** [comment]
Or stop using CSS zoom, and use `rem` instead. Zoom makes everything too hard.

**Comment by oleedd** [comment]
I have already easily fixed the problem above.
What is `rem`?

**Comment by rpkamp** [comment]
You fixed the current problems, but it seems zoom messes up all calculations, so there will be more. We need to get rid of it.

`rem` is like `em`, but relative to the root HTML element, instead of its parent.

**Comment by rpkamp** [comment]
When we use `rem` the size of the popup should change with the font size the user sets in the browser. If they have bad eyes and select a bigger font size, the popup will become bigger as well.

**Comment by oleedd** [comment]
> You fixed the current problems

Not all small. And can't currently fix the biggest - dragula's dragging. But it is interesting.

> `rem` is like `em`

You think I know what is `em`? No.

**Comment by rpkamp** [comment]
Lol. `em` is "the height of a capital M". It is a relative unit of height. If you increase the browser font size, any element with size defined in `em` will go bigger as well. It's like a zoom without using CSS zoom.

**Comment by oleedd** [comment]
Oh. I remember `em`. But it is a not popular unit. But I haven't heard about `rem`. Any links?
But anyway, you have to zoom favicons.

**Comment by oleedd** [comment]
Oh, I thought you mean some package. I remember `em`. But it is a not popular unit.
But anyway, you have to zoom favicons.

**Comment by rpkamp** [comment]
I know. But that's possible if you scale them with background stretch I think. Will have to try that later.

**Comment by rpkamp** [comment]
I've used `background-size` instead, and that works just fine. Zoom option is gone.

See https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/124

**Comment by oleedd** [comment]
But how to name my project option for small fonts when only the font size will be increased without increasing element sizes, favicons?

**Comment by rpkamp** [comment]
ClearFont? ReadableFont? ScaledFont?

**Comment by oleedd** [comment]
Really. But also need to use "size" like "clear font size" or "clear font scale". Or even "unaffect font size".
You are going to implement "affect font size" which affects all elements (like zoom).
But possible to use both at the same time. Because "unaffect font size" is the ratio between the element and the font.

**Comment by oleedd** [comment]
Or you can leave the "zoom" option but implement it using `font-size`.

**Comment by rpkamp** [comment]
Normalised font size maybe?

**Comment by oleedd** [comment]
No. not suitable. I like "unaffect font size" which doesn't affect anything else except itself.

**Comment by oleedd** [comment]
No. not suitable. I like "unaffect font size" which doesn't affect anything else except itself.
Or you can still use the "zoom" name and my option will be "font size".

**Comment by rpkamp** [comment]
If you can post your code we can see how and if it can be used in this extension.

**Comment by oleedd** [comment]
It is not ready yet. But with that, the font option will be perfect.
