### ISSUE TITLE
When moving items up/down the window should scroll up/down when you near the edges

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/chrome-minimal-bookmarks-tree#53]
As requested in chrome webstore

**Comment by oleedd** [comment]
If you have an access to "gu-mirror" clone element which is created while moving, I can give code for scrolling.

**Comment by oleedd** [comment]
If you have an access to "gu-mirror" cloned element which is created while moving, I can give code for scrolling.

**Comment by rpkamp** [comment]
I don't, I'm using [dragula](https://github.com/bevacqua/dragula)

**Comment by oleedd** [comment]
I know. But it is need to get a cloned element. As a variant just to get this element by class name.

**Comment by oleedd** [comment]
It is code for scrolling. You can check it just in console.
```javascript
document.onmousedown = function() {
	var clone, scroll;
	document.onmousemove = function() {
		document.onmouseup = function() {
			document.onmousemove = null;
		}
		if (!clone) {
			clone = document.querySelector('.gu-mirror');
		}
		if (clone && clone.getBoundingClientRect().bottom < document.documentElement.clientHeight) {
			clearInterval(scroll);
		}
		if (clone) {
			if (clone.getBoundingClientRect().bottom > document.documentElement.clientHeight) {
				var dif = clone.getBoundingClientRect().bottom - document.documentElement.clientHeight;
				clearInterval(scroll);
				scroll = setInterval(function() {            
                	clone.style.top = parseInt(clone.style.top) + 1;
					wrapper.scrollBy(0, 1);
				}, 250 / dif);
			}
			else if (clone.getBoundingClientRect().top < 0) {
				var dif = Math.abs(clone.getBoundingClientRect().top);
				clearInterval(scroll);
				scroll = setInterval(function() {
					clone.style.top = parseInt(clone.style.top) - 1;
					wrapper.scrollBy(0, -1);
				}, 250 / dif);
			}
		}
	}
}
`

**Comment by oleedd** [comment]
It is code for scrolling. You can check it just in console.
```javascript
document.onmousedown = function() {
	var clone, scroll;
	document.onmousemove = function() {
		document.onmouseup = function() {
			document.onmousemove = null;
		}
		if (!clone) {
			clone = document.querySelector('.gu-mirror');
		}
		if (clone && clone.getBoundingClientRect().bottom < document.documentElement.clientHeight) {
			clearInterval(scroll);
		}
		if (clone) {
			if (clone.getBoundingClientRect().bottom > document.documentElement.clientHeight) {
				var dif = clone.getBoundingClientRect().bottom - document.documentElement.clientHeight;
				clearInterval(scroll);
				scroll = setInterval(function() {            
                	clone.style.top = parseInt(clone.style.top) + 1;
					wrapper.scrollBy(0, 1);
				}, 250 / dif);
			}
			else if (clone.getBoundingClientRect().top < 0) {
				var dif = Math.abs(clone.getBoundingClientRect().top);
				clearInterval(scroll);
				scroll = setInterval(function() {
					clone.style.top = parseInt(clone.style.top) - 1;
					wrapper.scrollBy(0, -1);
				}, 250 / dif);
			}
		}
	}
}
```

**Comment by oleedd** [comment]
There is no work to do from your side. There is all done and works on my side. If to paste this to the extension console then scrolling works. Just need to paste it in any place of the pop-up script after you see that it really works.

**Comment by oleedd** [comment]
Does it work for you?

**Comment by rpkamp** [comment]
Haven't tried it yet, sorry. Too busy with other stuff.

**Comment by rpkamp** [comment]
Solved in v4.7.0, using https://www.npmjs.com/package/dom-autoscroller

It needed far less custom code and had some options in terms of scrolling speed, plus it animates nicely.

**Comment by oleedd** [comment]
I updated. But auto scrolling doesn't work. How to use it?

**Comment by rpkamp** [comment]
It somehow broke. I'll try and fix it later.

**Comment by oleedd** [comment]
![image](https://user-images.githubusercontent.com/36125949/53298691-36ca5880-383a-11e9-93ea-1a17dd3704ff.png)

**Comment by oleedd** [comment]
Any news?

**Comment by rpkamp** [comment]
Fixed in https://github.com/rpkamp/chrome-minimal-bookmarks-tree/pull/85

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1 and the same errors in the console.

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1 and the same errors in the console. Please firstly check working of the extension before uploading to chrome web store.
The problem is not in type of function. There is an error in minifier - there is `this.down` in github but in the web store version there is `m.down`. Just change it before uploading and it will work.
Also scrolling starts to work too early. It should work when a moved bookmark touches borders. But now users can not move a bookmark to the first or the last position of view without starting scrolling. Possible to reduce the distance to borders (the best is 0 mm, at least 1 mm)?

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1 and the same errors in the console. Please firstly check working of the extension before uploading to chrome web store.
The problem is not in type of function. There is an error in minifier - there is this.down in github but in the web store version there is m.down. Just change it before uploading and it will work.
Also scrolling starts to work too early. It should work when a moved bookmark touches borders. But now users can't move a bookmark to the first or the last position of view without starting scrolling. Now `margin` property` is 20 - it is 4 mm from borders. `margin` better to make 0 (at least 5).

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1 and the same errors in the console. Please firstly check working of the extension before uploading to chrome web store.
The problem is not in type of function. There is an error in minifier - there is this.down in github but in the web store version there is m.down. Just change it before uploading and it will work.
Also scrolling starts to work too early. It should work when a moved bookmark touches borders. But now users can't move a bookmark to the first or the last position of view without starting scrolling. Now `margin` property is 20 - it is 4 mm from borders. `margin` better to make 0 (at least 5).

**Comment by oleedd** [comment]
It still doesn't work in 4.8.1 and the same errors in the console. Please firstly check working of the extension before uploading to chrome web store.
The problem is not in type of function. There is an error in minifier - there is this.down in github but in the web store version there is m.down. Just change it before uploading and it will work.
Also scrolling starts to work too early. It should work when a moved bookmark touches borders. But now users can't move a bookmark to the first or the last position of view without starting scrolling. `margin` property better to make 0 (at least 10).
